### ISSUE TITLE
expanding the contents of the file hides all code in split view

### ISSUE THREAD

**Issue by disordered** [reviewninja/review.ninja#1027]
Works fine in unified, but in split view it just removes the entire diff.
```
TypeError: Cannot read property 'head' of null
    at https://review-ninja.mo.sap.corp/directives/diff.js:92:47
    at Array.forEach (native)
    at expandSplit (https://review-ninja.mo.sap.corp/directives/diff.js:91:27)
    at https://review-ninja.mo.sap.corp/directives/diff.js:114:52
    at https://review-ninja.mo.sap.corp/api.js:100:21
    at https://review-ninja.mo.sap.corp/api.js:38:25
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:9408:11
    at processQueue (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:13248:27)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:13264:27
    at Scope.$eval (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:14466:28)
```

not sure if related, but there is also this error on load:
```
TypeError: markdown.replace is not a function
    at label (Markdown.js:16)
    at Markdown.js:44
    at api.js:100
    at api.js:38
    at angular.js:9408
    at processQueue (angular.js:13248)
    at angular.js:13264
    at Scope.$eval (angular.js:14466)
    at Scope.$digest (angular.js:14282)
    at Scope.$apply (angular.js:14571)
```

**Comment by dfarr** [comment]
I have not been able to replicate this. Will close for now, will reopen if it pops up again.
